### ISSUE TITLE
Installation error: unexpected input parsing error

### ISSUE THREAD

**Issue by samnooij** [karchern/ggquantileplot#9]
I'm using R version 4.0.2 with tidyverse 1.3.0, although I had not loaded any packages yet. When I try to install the package using the provided command: `devtools::install_github('https://github.com/karchern/ggquantileplot/tree/main')`, I run into an error (see below).
It appears that my R does not like the backslash in line 199 of [`R/main.r`](../blob/main/R/main.r). I noticed there are a few instances of backslashes in `R/unility.r` as well. If I replace all of those by 'function', I can install the package without further problems. Would it be possible to provide extra instructions for installation, or adapt the code to make it work with other versions? Thanks!

```
* installing *source* package ‘ggquantileplot’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /tmp/RtmpnDKyXw/R.INSTALL36a974173ae58d/ggquantileplot/R/main.r:199:18: unexpected input
198: 
199:     r <- map(qs, \
                      ^
ERROR: unable to collate and parse R files for package ‘ggquantileplot’
* removing ‘/home/snooij/R/x86_64-pc-linux-gnu-library/4.0/ggquantileplot’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp8avzJL/file36a02a56ad7ec1/ggquantileplot_0.0.0.9000.tar.gz’ had non-zero exit status
```

**Comment by karchern** [comment]
Hi Sam,

thanks for checking this out. The `\(x)` syntax is something to newer versions of tidyverse. 

I replaced them with regular `function(x)` calls so this should be fixed now
